version: "3.8"

services:
  fitness-app:
    image: 3bok/fitness-app:latest
    container_name: fitness-app
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3013:3013"
    volumes:
      - fitness-db:/app/db
    environment:
      - NODE_ENV=production
      - PORT=3013
      - HOSTNAME=0.0.0.0
    networks:
      - staging-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3013",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  fitness-db:
    driver: local

networks:
  staging-network:
    external: true
