name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Tag with GitVersion
        uses: michielvha/gitversion-tag-action@main
        id: gitversion
        with:
          configFilePath: 'gitversion.yml'


      - name: Build and Push Docker Image
        uses: michielvha/docker-release-action@main
        with:
          username: 3bok
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          project: ${{ github.event.repository.name }}
          version: ${{ steps.gitversion.outputs.semver }}
